//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the tool.
// Runtime Version: 4.0.30319.42000
//
// Changes to this file may cause incorrect behavior and
// disappears if the code is rebuilt.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUBESP.Properties {
    using System;
    
    
    /// <summary>
    ///  Strictly typed resource class for operations such as searching localized strings.
    /// </summary>
    // This class is StronglyTypedResourceBuilder using a tool like ResGen or Visual Studio
    // Created automatically by the // class.
    // Edit your .ResX file to add or remove members and then ResGen
    // Re-run the command with the / str option or rebuild your VS project
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///  Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PUBESP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///  Overrides the CurrentUICulture property of the current thread for all
        ///  Overrides the CurrentUICulture property for all resource searches.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
