//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the tool.
// Runtime Version: 4.0.30319.42000
//
// Changes to this file may cause incorrect behavior and
// disappears if the code is rebuilt.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUBESP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
